services:
  - type: web
    name: docque-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: PORT
        value: 10000
      - key: LOG_LEVEL
        value: INFO
      - key: DATA_DIR
        value: /opt/render/project/src/data
      - key: OPENAI_API_KEY
        sync: false  # This should be set in Render dashboard
    healthCheckPath: /health
    disk:
      name: docque-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1